name: Django App Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Replace with your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt  # Adjust the path as needed

      - name: Set DJANGO_SETTINGS_MODULE
        run: echo "export DJANGO_SETTINGS_MODULE=djangoproject.settings" >> $GITHUB_ENV

      - name: Test App Code
        run: python djangoproject/manage.py test weather_news.tests
